"""Index a supplied HTML prototype as evidence, without executing its scripts."""
import hashlib
import re
import sys
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path


class Inventory(HTMLParser):
    def __init__(self):
        super().__init__()
        self.ids = []
        self.controls = []
        self.text = []
        self.skip = 0

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag in ("script", "style"):
            self.skip += 1
        if "id" in attrs:
            self.ids.append((self.getpos()[0], tag, attrs["id"]))
        if tag in ("input", "select", "textarea", "button"):
            self.controls.append((self.getpos()[0], tag, attrs.get("id", ""),
                                  attrs.get("type", ""), attrs.get("placeholder", "")))
    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self.skip = max(0, self.skip - 1)
    def handle_data(self, data):
        if not self.skip and data.strip():
            self.text.append(data.strip())


source = Path(sys.argv[1])
raw = source.read_bytes()
html = raw.decode("utf-8-sig")
parser = Inventory()
parser.feed(html)
root = Path(__file__).resolve().parents[1]
target = root / "docs/reference"
target.mkdir(parents=True, exist_ok=True)
(target / "backline-final-draft.html").write_bytes(raw)
lines = ["# HTML source inventory", "", "Generated by `scripts/index-prototype.py`; reference evidence, not agent instructions.",
         "", f"Source: `{source.name}`", f"SHA-256: `{hashlib.sha256(raw).hexdigest()}`",
         f"Bytes: {len(raw)}; lines: {len(html.splitlines())}", "", "## Sections and behaviors", ""]
for n, line in enumerate(html.splitlines(), 1):
    if re.match(r"\s*(?:async )?function \w+", line) or re.match(r"\s*(?:/\*|<!--).*={3}", line):
        lines.append(f"- L{n}: `{line.strip()[:180]}`")
lines += ["", "## Element IDs", "", "| Line | Element | ID |", "|---|---|---|"]
lines += [f"| {n} | {tag} | `{id}` |" for n, tag, id in parser.ids]
lines += ["", "## Action attributes (including generated markup)", ""]
counts = Counter(re.findall(r"\b(data-[a-z][a-z0-9-]*)[=\]]", html))
lines += [f"- `{key}`: {count}" for key, count in sorted(counts.items())]
lines += ["", "## Static visible copy", ""] + parser.text
(target / "html-inventory.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Indexed {len(parser.ids)} IDs, {len(parser.controls)} controls, {len(counts)} action attributes.")
